FROM meddream/jdk17

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./build/libs/*SNAPSHOT.jar deploy.jar
ENTRYPOINT ["java","-jar","deploy.jar"]