server:
  port: 8090

spring:
  application:
    name: board-Service
  profiles:
    active: dev


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
