eureka:
  instance:
    hostname: 144.24.87.198
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: https://144.24.87.198:8188/eureka
  server:
    enable-self-preservation: f
    alse