eureka:
  instance:
    hostname: 144.24.87.198
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:8188/eureka
  server:
    enable-self-preservation: false