server:
  port: 8080

spring:
  application:
    name: user-Service
  profiles:
    active: dev


eureka:
  instance:
    hostname: sub.junnyland.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://sub.junnyland.com:8761/eureka
