server:
  port: 8761

eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: peer1.api-discovery.com
    secure-port: ${server.port}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://peer2.api-discovery.com:8762/eureka