eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: dev.api-discovery.com
    secure-port: ${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    disable-delta: true