eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: dev.api-discovery.com
    secure-port: ${server.port}
  client:
    service-url:
      defaultZone: http://dev.api-discovery.com:8761/eureka
    disable-delta: true